### ISSUE TITLE
AssertionError: backward pass is invalid for module in evaluation mode

### ISSUE THREAD

**Issue by bakingeol** [OpenLLMAI/OpenRLHF#118]
``Hi, thank you for making this repo!

An error occurred while training the PPO model. Polyglot 15.8b was used as the SFT model and polyglot5.8B was used as the reward model. I changed the model part by performing quantization and adding lora, but an error occurred regarding the backward pass.

Does anyone know how to solve this?

The contents below are the part where the error occurred, the part where the SFT and RM model were changed, and the part changed in the learning code.

thank you

```
Train epoch [1/1]:   0%|                                                                                                                                                                              | 0/1 [00:18<?, ?it/s]
Episode [1/1]:   0%|                                                                                                                                                                               | 0/2367 [12:56<?, ?it/s]
Traceback (most recent call last):
  File "ppo_test.py", line 244, in <module>
    trainer.fit(
  File "/raid2/baekig/OpenLLaMA2/openllama2/trainer/ppo_trainer.py", line 184, in fit
    status = self.ppo_train()
  File "/raid2/baekig/OpenLLaMA2/openllama2/trainer/ppo_trainer.py", line 223, in ppo_train
    status = self.training_step(experience)
  File "/raid2/baekig/OpenLLaMA2/openllama2/trainer/ppo_trainer.py", line 304, in training_step
    self.strategy.backward(critic_loss, self.critic, self.critic_optim)
  File "/raid2/baekig/OpenLLaMA2/openllama2/utils/deepspeed.py", line 97, in backward
    model.backward(loss)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1890, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2029, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 169, in backward
    ctx.pre_backward_function(ctx.module)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 436, in _run_before_backward_function
    self.pre_sub_module_backward_function(sub_module)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/raid2/baekig/anaconda3/envs/nlp/lib/python3.8/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 512, in pre_sub_module_backward_function
    assert sub_module.training, "backward pass is invalid for module in evaluation mode"
````

```python
strategy = get_strategy(args)
...
sft_id ='EleutherAI/polyglot-ko-12.8b' 
rm_id = 'EleutherAI/polyglot-ko-5.8b'
actor = Actor(sft_id, bnbconfig)  # SFT
critic = Critic(rm_id, bnbconfig)  # RM
reward_model = RewardModel(rm_id, bnbconfig)  # RM

actor.gradient_checkpointing_enable()
critic.gradient_checkpointing_enable()
actor.model.config.use_cache = False
reward_model.model.config.use_cache = False

initial_model = deepcopy(actor)  # SFT
critic.model = deepcopy(reward_model.model)
critic.value_head = deepcopy(reward_model.value_head)
critic.mean = deepcopy(reward_model.mean)
critic.std = deepcopy(reward_model.std)
initial_model.gradient_checkpointing_enable()
reward_model.gradient_checkpointing_enable()
critic.model.config.use_cache = False
initial_model.model.config.use_cache = False

actor.train()
critic.train()
initial_model.train()
reward_model.train()
...
tokenizer = get_tokenizer(args.pretrain, actor.model, "left", strategy)
get_tokenizer(args.critic_pretrain, critic.model, "left", strategy)
get_tokenizer(args.critic_pretrain, reward_model.model, "left", strategy)

dataset = PromptDataset(data, strategy) 
prompts_dataloader = strategy.setup_dataloader(dataset, 
                args.micro_rollout_batch_size, True, True)

actor_optim = strategy.create_optimizer(
    actor, lr=args.actor_learning_rate, betas=(0.9, 0.95), weight_decay=args.l2
...
)
```

```python
class Actor(nn.Module):
    """
    Actor model base class.

    Args:
        model (nn.Module): Actor Model.
        lora_rank (int): LoRA rank.
        lora_train_bias (str): LoRA bias training mode.
    """

    def __init__(
        self,
        pretrain_or_model,
        bnbconfig,
        from_config=False,
        lora_rank: int = 0,
        lora_train_bias: str = "none",
    ) -> None:
        super().__init__()

        self.model = AutoModelForCausalLM.from_pretrained(
            pretrain_or_model, torch_dtype=torch.bfloat16, 
            quantization_config = bnbconfig,
            trust_remote_code=True,
            device_map = {"":0}
        )
        self.model = PeftModel.from_pretrained(self.model, 'ingeol/sft_adapter', is_trainable=True)

class Critic(nn.Module):
# ...This part is the same as the SFT code, except for the adapter.

class RewardModel(nn.Module):
# ... This part is the same as the SFT code, except for the adapter.

```

Thank you for creating a great repo.

**Comment by bakingeol** [comment]
when i try this code stage2 it work! but i don't know why stage3 is not work,,,

**Comment by bakingeol** [comment]
thank you for reply

**Comment by catqaq** [comment]
This week we'll try to figure it out

**Comment by catqaq** [comment]
test with the latest code, please. 
This issue is related to the model being incorrectly set to eval mode and not being reverted back to train mode during the backward operation. It should be fixed in the latest code.

**Comment by catqaq** [comment]
feel free to reopen it~

**Comment by bakingeol** [comment]
thank you and sorry for late response. i will check this tomorrow ! thank you!!!!

**Comment by bakingeol** [comment]
i run this code and it work!! thank you!!!

**Comment by catqaq** [comment]
nice!
