### ISSUE TITLE
baichuan2-13b-base作为actor RuntimeError: CUDA error: device-side assert triggered   

### ISSUE THREAD

**Issue by netrookiecn** [OpenLLMAI/OpenRLHF#159]
首先非常感谢这个库，可以让多个13b的模型进行rlhf并起到不错的效果。 

问题：在 https://huggingface.co/baichuan-inc/Baichuan2-13B-Base进行内部多轮数据sft后的对齐模型 + openrlhf 提供的 rm-anthropic_hh-lmsys-oasst-webgpt.pt 出现异常如下

(CriticModelRayActor pid=1501276) ../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [205,0,0], thread: [39,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/tmp/ray/session_2023-12-14_16-24-38_024033_1489858/runtime_resources/working_dir_files/_ray_pkg_7135c6986d32e182/training/train_ppo_ray.py", line 159, in <module>
    train(args)
  File "/tmp/ray/session_2023-12-14_16-24-38_024033_1489858/runtime_resources/working_dir_files/_ray_pkg_7135c6986d32e182/training/train_ppo_ray.py", line 78, in train
    ray.get(refs)
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::ActorModelRayActor.fit() (pid=1500971, ip=0.0.0.0, actor_id=2423ef6409009064be14315003000000, repr=<openrlhf.trainer.ray.ppo_actor.ActorModelRayActor object at 0x7ed7a847b3d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2023-12-14_16-24-38_024033_1489858/runtime_resources/working_dir_files/_ray_pkg_7135c6986d32e182/openrlhf/trainer/ray/ppo_actor.py", line 146, in fit
    trainer.fit(self.prompts_dataloader, self.pretrain_dataloader,
  File "/tmp/ray/session_2023-12-14_16-24-38_024033_1489858/runtime_resources/working_dir_files/_ray_pkg_7135c6986d32e182/openrlhf/trainer/ppo_trainer.py", line 161, in fit
    experience = self.experience_maker.make_experience(**inputs, **self.generate_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2023-12-14_16-24-38_024033_1489858/runtime_resources/working_dir_files/_ray_pkg_7135c6986d32e182/openrlhf/trainer/ppo_utils/experience_maker.py", line 201, in make_experience
    base_action_log_probs, value, r = ray.get([base_action_log_probs_ref, value_ref, r_ref])
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.RayTaskError(RuntimeError): ray::CriticModelRayActor.forward() (pid=1501276, ip=0.0.0.0, actor_id=75184ac68172839ef0c6dc9803000000, repr=<openrlhf.trainer.ray.ppo_critic.CriticModelRayActor object at 0x7f6a8f248dd0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2023-12-14_16-24-38_024033_1489858/runtime_resources/working_dir_files/_ray_pkg_7135c6986d32e182/openrlhf/trainer/ray/ppo_critic.py", line 119, in forward
    value = self.critic(sequences.to(device), action_mask.to(device), attention_mask.to(device))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1807, in forward
    loss = self.module(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2023-12-14_16-24-38_024033_1489858/runtime_resources/working_dir_files/_ray_pkg_7135c6986d32e182/openrlhf/models/critic.py", line 56, in forward
    outputs = self.model(sequences, attention_mask=attention_mask)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 883, in forward
    if 0 in attention_mask:
       ^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/rlhf/lib/python3.11/site-packages/torch/_tensor.py", line 997, in __contains__
    return (element == self).any().item()  # type: ignore[union-attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered   

背景：使用8*A800  openrlhf框架进行PPO训练
参数如下：ray job submit --address="http://127.0.0.1:8265" \
    --runtime-env-json='{"working_dir": "."}' \
    -- python training/train_ppo_ray.py \
    --ref_num_nodes 1 \
    --ref_num_gpus_per_node 1 \
    --reward_num_nodes 1 \
    --reward_num_gpus_per_node 1 \
    --critic_num_nodes 1 \
    --critic_num_gpus_per_node 2 \
    --actor_num_nodes 1 \
    --actor_num_gpus_per_node 4 \
    --pretrain /baichuan2-13b-base \
    --critic_pretrain /tmp/llama2base/models--meta-llama--Llama-2-13b-hf/snapshots/1f3a61cf48cd578461427f32fa858097296a4236 \
    --reward_model_path /tmp/openrlhf_checkpoint/rm-anthropic_hh-lmsys-oasst-webgpt.pt \
    --sft_model_path /multiturn_2023_12_13_23_44_48/checkpoint-150/baichuan_sft_13bbase20231214.pt \
    --save_path /testRlhf/jxloutput \
    --micro_train_batch_size 2 \
    --train_batch_size 128 \
    --micro_rollout_batch_size 4 \
    --rollout_batch_size 1024 \
    --max_epochs 1 \
    --prompt_max_len 2048 \
    --generate_max_len 2048 \
    --zero_stage 2 \
    --actor_learning_rate 5e-7 \
    --critic_learning_rate 9e-6 \
    --inference_tp_size 1 \
    --init_kl_coef 0.01 \
    --prompt_data promptdata \
    --normalize_reward \
    --actor_init_on_gpu \
    --adam_offload \
    --gradient_checkpointing \
    --bf16 \
    --save_hf_model \

尝试1： 将Baichuan2-13B-Base 换成 deepseek-coder 6.7b重新进行内部数据sft，再结合rm-anthropic_hh-lmsys-oasst-webgpt.pt 。结果很正常
尝试2： 将Baichuan2-13B-Base 换成 deepseek-coder 6.7b重新进行内部数据sft，将rm-anthropic_hh-lmsys-oasst-webgpt.pt 换成https://huggingface.co/GAIR/autoj-13b 
结果正常
尝试3：根据 https://github.com/PKU-Alignment/safe-rlhf/issues/9 这个issue查看是否可能是Tokenizer的问题。经检查，词表和embed均为 125696

疑惑：改变的是baichuan和deepseek，但看报错又是在modeling_llama.py   不太清楚ray这个框架怎么debug 
辛苦提些意见

**Comment by hijkzzz** [comment]
OpenRLHF 的设计默认是 actor critic 用同一个模型来的，所以如果tokenizer不同可能会造成问题。

**Comment by catqaq** [comment]
@netrookiecn I remember that this issue seems to be related to the number of categories (which should be different from the tokenizer in this context)? Can you help to confirm this, please?
We will check this issue as soon as possible, but we have been really busy lately, so it might not be very soon. If it is indeed caused by differences in the tokenizer, we will consider supporting heterogeneous models in the future, but again, it won't be very soon.

**Comment by netrookiecn** [comment]
Thanks for answering  
1、When I try to change to baichuan2-base as actor/sft，baichuan2-chat as rewardd/critic, it works . but i am not clear about  openrlhf's theory, need time to  figure out why
2、what do you mean about "he number of categories  " @catqaq 
3、even the same model architecture of model but diffierent  base tokenizer , can not work,  such as  baichuan2_base(vocab_size=125696) as sft and baichuan1_chat(vocab=64000)

**Comment by catqaq** [comment]
@netrookiecn 
1.This is due to historical reasons; in previous implementations, all the models were homogeneous.
2.number of categories -> vocab size
3.The difference in vocabularies is the reason for the inconsistency in the number of categories.

**Comment by netrookiecn** [comment]
thanks for your reply
