### ISSUE TITLE
AssertionError: mismatch size output_state_dict(148) and state_dict(149) sft training

### ISSUE THREAD

**Issue by qwenzo** [OpenLLMAI/OpenRLHF#274]
Hello, 

when I try to train gpt2 model I get the error `AssertionError: mismatch size output_state_dict(148) and state_dict(149)` 

Error:

```
Traceback (most recent call last):███████████████| 11137/11137 [1:01:01<00:00,  3.48it/s, gpt_loss=2.22, loss_mean=2.24]
  File "/nfs/homedirs/user/code/p1/p/OpenRLHF/examples/train_sft.py", line 181, in <module>
    train(args)
  File "/nfs/homedirs/user/code/p1/p/OpenRLHF/examples/train_sft.py", line 114, in train
    strategy.save_model(model, tokenizer, args.save_path)
  File "/nfs/homedirs/user/.local/lib/python3.10/site-packages/openrlhf/utils/deepspeed.py", line 285, in save_model
    assert len(output_state_dict) == len(
AssertionError: mismatch size output_state_dict(148) and state_dict(149)
Traceback (most recent call last):
  File "/nfs/homedirs/user/code/p1/p/OpenRLHF/examples/train_sft.py", line 181, in <module>
    train(args)
  File "/nfs/homedirs/user/code/p1/p/OpenRLHF/examples/train_sft.py", line 114, in train
    strategy.save_model(model, tokenizer, args.save_path)
  File "/nfs/homedirs/user/.local/lib/python3.10/site-packages/openrlhf/utils/deepspeed.py", line 285, in save_model
    assert len(output_state_dict) == len(
AssertionError: mismatch size output_state_dict(148) and state_dict(149)
```

Here are all the arguments i use for `train_sft.py` (with default showing the value I'm using).

```
parser.add_argument("--pretrain", type=str, default="gpt2")
parser.add_argument("--dataset", type=str, default="Open-Orca/OpenOrca")
parser.add_argument("--dataset_probs", type=str, default="1.0", help="sampling probs for datasets")
parser.add_argument("--save_path", type=str, default="./ckpt/sft")
parser.add_argument("--save_steps", type=int, default=-1)
parser.add_argument("--logging_steps", type=int, default=1)
parser.add_argument("--eval_steps", type=int, default=2500)
parser.add_argument("--ckpt_path", type=str, default="./ckpt/checkpoints_sft")
parser.add_argument("--max_ckpt_num", type=int, default=1)
parser.add_argument("--max_ckpt_mem", type=int, default=1000)  # 1000GB
parser.add_argument("--max_epochs", type=int, default=2)
parser.add_argument("--micro_train_batch_size", type=int, default=8)
parser.add_argument("--train_batch_size", type=int, default=128)
parser.add_argument("--max_samples", type=int, default=100_000)
parser.add_argument("--max_len", type=int, default=512)
parser.add_argument("--max_norm", type=float, default=1.0)
parser.add_argument("--l2", type=float, default=0)
parser.add_argument("--lr_scheduler", type=str, default="cosine")
parser.add_argument("--load_checkpoint", action="store_true", default=False)
parser.add_argument("--pretrain_mode", action="store_true", default=False)

parser.add_argument("--gradient_checkpointing", action="store_true", default=False)
parser.add_argument("--seed", type=int, default=42)
parser.add_argument("--local_rank", type=int, default=-1, help="local_rank for deepspeed")
parser.add_argument("--zero_stage", type=int, default=2)
parser.add_argument("--bf16", action="store_true", default=False)
parser.add_argument("--learning_rate", type=float, default=2e-6)
parser.add_argument("--zpg", type=int, default=1, help="ZeRO++ max partition size")
parser.add_argument("--adam_offload", action="store_true", default=False)
parser.add_argument("--flash_attn", action="store_true", default=False)
parser.add_argument("--aux_loss_coef", type=float, default=0)
parser.add_argument("--grad_accum_dtype", type=str, default=None)
parser.add_argument("--disable_trace_cache", action="store_true", default=False)
parser.add_argument("--load_in_4bit", action="store_true", default=False)
parser.add_argument("--lora_rank", type=int, default=0)
parser.add_argument("--lora_alpha", type=int, default=16)
parser.add_argument("--target_modules", type=list, default=None)
parser.add_argument("--input_template", type=str, default="Human: {}\nAssistant: ")
parser.add_argument("--gradient_checkpointing_use_reentrant", action="store_true")
parser.add_argument("--disable_fast_tokenizer", action="store_true", default=False)

parser.add_argument("--bos_token", type=str, default=None)
parser.add_argument("--eos_token", type=str, default=None)
parser.add_argument("--pad_token", type=str, default=None)
parser.add_argument("--unk_token", type=str, default=None)

# custom dataset key name
parser.add_argument("--input_key", type=str, default=None)
parser.add_argument("--output_key", type=str, default=None)

# wandb pamameters
parser.add_argument("--use_wandb", type=str, default=True)
parser.add_argument("--wandb_org", type=str, default=None)
parser.add_argument("--wandb_group", type=str, default=None)
parser.add_argument("--wandb_project", type=str, default="openrlhf_train_sft")
parser.add_argument(
    "--wandb_run_name",
    type=str,
    default="sft_%s" % datetime.now().strftime("%m%dT%H:%M"),
)
```

**Comment by hijkzzz** [comment]
It is just a special case.
