### ISSUE TITLE
vllm engine not working

### ISSUE THREAD

**Issue by babu111** [OpenLLMAI/OpenRLHF#358]
I'm using the vllm engine demo at vllm_engine.py

llm = LLMRayActor.remote("/share/checkpoints/Meta-Llama-3-8B-Instruct", tensor_parallel_size=4)
output = ray.get(llm.generate.remote("San Franciso is a"))
print(f"output: {output}")

and get the following error

Traceback (most recent call last):
  File "/share/OpenRLHF/openrlhf/trainer/ray/vllm_engine.py", line 120, in <module>
    output = ray.get(llm.generate.remote("San Franciso is a"))
  File "/share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/ray/_private/worker.py", line 2623, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/ray/_private/worker.py", line 863, in get_objects
    raise value
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task, ray::LLMRayActor.__init__() (pid=236832, ip=0.0.0.0, actor_id=310c5f405ee4130f2335d35902000000, repr=<vllm_engine.LLMRayActor object at 0x7ff1c965d870>)
  File "/share/OpenRLHF/openrlhf/trainer/ray/vllm_engine.py", line 46, in __init__
    self.llm = vllm.LLM(*args, **kwargs)
  File "/share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 123, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 282, in from_engine_args
    initialize_ray_cluster(engine_config.parallel_config)
  File "/share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/vllm/executor/ray_utils.py", line 79, in initialize_ray_cluster
    ray.init(address=ray_address, ignore_reinit_error=True)
  File "/share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/ray/client_builder.py", line 376, in client
    builder = _get_builder_from_address(address)
  File "/share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/ray/client_builder.py", line 344, in _get_builder_from_address
    assert "ClientBuilder" in dir(
AssertionError: Module: http does not have ClientBuilder.

my env are as follows:
vllm 0.4.2
ray[default]==2.12.0
transformers  4.41.0

**Comment by babu111** [comment]
and when I run the examples/scripts/train_ppo_llama_ray.sh, the process gets stuck. I suspect this was the vllm engine issue, so I ran the example but still failed.

**Comment by hijkzzz** [comment]
please use vllm 0.4.2

**Comment by babu111** [comment]
do you have an existing image I can pull?
I'm using the nvidia ngc 24.02 container following the instruction.
however, when installing vllm==0.4.2, pip installs torch==2.3.0, which causes the following issue
https://github.com/chenfei-wu/TaskMatrix/issues/116
I tried pip uninstall transformer-engine, but it doesn't work either

**Comment by hijkzzz** [comment]
It should work with train_ppo_ray.py

**Comment by babu111** [comment]
after reconstructing the environment from scratch, this issue was solved
